// Localized content for the reflective Personal Growth feature.
// It intentionally describes flexible tendencies, not fixed personality types.
const GROWTH_TRAITS = ["feeling", "thinking", "reflective", "expressive"];
const GROWTH_QUIZ_SCORES = [
    [["feeling", "reflective"], ["thinking", "reflective"], ["expressive", "feeling"]],
    [["reflective", "feeling"], ["expressive", "thinking"], ["thinking", "reflective"]],
    [["feeling", "expressive"], ["thinking", "expressive"], ["reflective", "thinking"]],
    [["reflective", "thinking"], ["feeling", "reflective"], ["expressive", "feeling"]],
    [["thinking", "reflective"], ["expressive", "thinking"], ["feeling", "expressive"]],
    [["feeling", "reflective"], ["thinking", "expressive"], ["expressive", "feeling"]]
];

const growthCopy = {
    id: {
        nav: "Growth", kicker: "KENALI POLAMU", title: "Personal Growth 🌱",
        subtitle: "Kenali pola responsmu, lalu pilih respons yang lebih sesuai dengan nilai dan kebutuhanmu.",
        introKicker: "MULAI DARI REFLEKSI KECIL", introTitle: "Bagaimana kamu biasanya merespons?",
        introText: "Jawab enam situasi singkat. Tidak ada jawaban benar atau salah—hasilnya adalah kecenderungan, bukan label permanen.",
        flow: ["Rasakan", "Pahami", "Pilih"], start: "Mulai refleksi", privacy: "🔒 Jawaban dan profil tersimpan di browser ini.",
        step: "Pertanyaan {current} dari {total}", questionHint: "Pilih jawaban yang paling mendekati respons alammu.", back: "Kembali",
        profileKicker: "HOW I TEND TO RESPOND", retake: "Ulangi refleksi", profileLabel: "Kecenderungan utamamu",
        mixLabel: "Juga tampak dalam caramu merespons", disclaimer: "Profil ini fleksibel dan dapat berubah sesuai situasi—bukan diagnosis atau label kepribadian.",
        mapKicker: "GROWTH PROFILE", mapTitle: "Peta pertumbuhanmu", mapLabels: ["SIAPA AKU", "YANG PERLU DIJAGA", "CARA BERTUMBUH"],
        triggersKicker: "RESPONSE TRIGGERS", triggersTitle: "Momen yang perlu diperhatikan", triggerLabels: ["Saat aku merasakan", "Respons alaminya", "Coba alihkan menjadi"],
        compassKicker: "RESPONSE COMPASS", compassTitle: "Jeda sebelum bereaksi", compassIntro: "Tiga langkah singkat untuk membuat emosi tetap didengar tanpa membiarkannya mengambil alih.",
        compass: [
            { icon: "♡", label: "FEEL", title: "Namai perasaan", text: "Apa yang sedang kurasakan dan di mana terasa di tubuh?" },
            { icon: "◇", label: "THINK", title: "Pisahkan fakta", text: "Apa yang benar-benar terjadi, dan apa yang masih berupa asumsi?" },
            { icon: "↗", label: "RESPOND", title: "Pilih langkah", text: "Respons apa yang jujur, aman, dan sesuai kebutuhanku?" }
        ],
        coachKicker: "RESPONSE COACH", coachTitle: "Susun respons yang lebih sadar", coachIntro: "Ceritakan situasi atau tempel draf pesan. Panduan akan menyesuaikan dengan kecenderungan responsmu.",
        situationTab: "Situasi", draftTab: "Draf pesan", situationLabel: "Ceritakan situasimu", draftLabel: "Tempel draf pesanmu",
        situationPlaceholder: "Contoh: Temanku membatalkan janji tanpa memberi kabar...", draftPlaceholder: "Contoh: Kamu selalu begini. Aku capek dan tidak mau bicara lagi!",
        coachButtonSituation: "Bantu aku merespons", coachButtonDraft: "Tinjau sebelum dikirim", coachEmpty: "Tulis situasi atau draf pesan terlebih dahulu.",
        coachDisclaimer: "Panduan reflektif lokal, bukan diagnosis atau pengganti tenaga profesional.",
        coachHeadings: ["Yang mungkin kamu rasakan", "Yang mungkin sedang terjadi", "Sebelum merespons", "Respons yang bisa dicoba"],
        emotionFallback: "emosi yang campur aduk", neutralSituation: "Ada jarak antara kejadian yang kamu lihat dan makna yang kamu berikan. Cek faktanya sebelum menyimpulkan niat orang lain.",
        neutralDraft: "Pesanmu membawa kebutuhan yang penting. Membuatnya spesifik dan berfokus pada satu kejadian akan mengurangi kemungkinan lawan bicara menjadi defensif.",
        responseTemplate: "Aku merasa {emotion} ketika {event}. Aku ingin memahami apa yang terjadi. Bisakah kita membicarakannya dan mencari langkah yang jelas?",
        draftResponseTemplate: "Aku ingin menyampaikan ini dengan lebih tenang. Saat hal itu terjadi, aku merasa {emotion}. Yang kubutuhkan adalah kejelasan. Bisakah kita membicarakan langkah berikutnya?",
        tendencyReminder: "Sebagai {name}, kamu mungkin perlu {tip}", coachDone: "Sesi refleksi tersimpan.",
        dailyKicker: "DAILY SCENARIO", dailyTitle: "Latihan hari ini", dailyPrompt: "Apa respons yang paling ingin kamu latih?", dailyDone: "Latihan hari ini selesai", dailyAgain: "Kamu boleh meninjau pilihan lain tanpa mengubah jawaban hari ini.",
        practiceLabel: "latihan selesai", coachCountLabel: "sesi refleksi", aboutLink: "Tentang, privasi & pengingat →", aboutBack: "← Kembali ke Personal Growth",
        questions: [
            { icon: "🌧️", text: "Rencana penting tiba-tiba berubah. Apa yang paling mungkin kamu lakukan?", options: ["Merasakan kecewanya dulu sebelum memutuskan langkah", "Mencari fakta dan pilihan pengganti", "Langsung menghubungi orang terkait untuk membicarakannya"] },
            { icon: "💬", text: "Seseorang memberi kritik yang terasa tajam. Respons pertamamu?", options: ["Diam sejenak untuk mencerna perasaanku", "Menjelaskan sudut pandangku saat itu juga", "Memeriksa bagian kritik yang faktual"] },
            { icon: "🤝", text: "Seorang teman bercerita tentang masalahnya. Kamu biasanya...", options: ["Mendengarkan dan memvalidasi perasaannya", "Membantu menyusun solusi yang praktis", "Memberi ruang lalu menanyakan apa yang ia butuhkan"] },
            { icon: "⚡", text: "Konflik mulai memanas. Apa kecenderungan alammu?", options: ["Mundur sebentar agar pikiranku lebih jernih", "Menjaga perasaan semua orang tetap aman", "Mengungkapkan dengan langsung apa yang menggangguku"] },
            { icon: "🧩", text: "Kamu harus membuat keputusan yang sulit. Apa pegangan utamamu?", options: ["Menimbang bukti dan konsekuensi", "Mendiskusikannya untuk menguji pikiranku", "Memilih yang paling selaras dengan nilai dan perasaanku"] },
            { icon: "🌱", text: "Setelah melakukan kesalahan, apa yang paling sering terjadi?", options: ["Aku memikirkan dampaknya pada orang lain", "Aku mencari pelajaran dan segera memperbaiki", "Aku mengakuinya secara terbuka dan meminta maaf"] }
        ],
        tendencies: {
            feeling: { icon: "💗", name: "Perasa Empatik", short: "peka dan terhubung", summary: "Kamu cenderung membaca situasi melalui perasaan, nilai, dan dampaknya pada orang lain.", who: "Kehangatan dan empati membantumu menangkap hal yang tidak selalu terucap.", watch: "Kebutuhan orang lain dapat terdengar lebih keras daripada kebutuhanmu sendiri.", grow: "Validasi perasaanmu, lalu tanyakan fakta dan batas apa yang kamu perlukan.", coachTip: "memisahkan empati dari tanggung jawab atas semua perasaan orang", triggers: [
                ["Orang lain tampak kecewa", "Segera menyalahkan diri atau ingin memperbaiki semuanya", "Tanyakan apa yang sebenarnya mereka butuhkan"],
                ["Hubungan terasa menjauh", "Mengisi kekosongan dengan asumsi", "Sebutkan pengamatanmu dan minta kejelasan"]
            ] },
            thinking: { icon: "🔎", name: "Penjernih Pola", short: "logis dan terarah", summary: "Kamu cenderung mencari fakta, pola, dan solusi yang dapat membuat situasi lebih jelas.", who: "Kejernihan berpikirmu membantu mengurai masalah yang terasa rumit.", watch: "Solusi yang cepat kadang datang sebelum perasaan sempat didengar.", grow: "Akui emosi yang hadir sebelum menawarkan analisis atau jalan keluar.", coachTip: "memberi ruang pada emosi sebelum berpindah ke solusi", triggers: [
                ["Situasi terasa tidak masuk akal", "Membantah atau memperbaiki detail", "Tanyakan bagian mana yang paling penting bagi orang lain"],
                ["Masalah belum punya solusi", "Menekan diri untuk segera menemukan jawaban", "Tentukan satu fakta dan satu langkah kecil saja"]
            ] },
            reflective: { icon: "🌙", name: "Pengamat Tenang", short: "mendalam dan berhati-hati", summary: "Kamu cenderung mengambil jarak untuk memahami perasaan dan konteks sebelum bertindak.", who: "Jeda membantumu melihat nuansa dan menghindari respons yang tergesa-gesa.", watch: "Terlalu lama memproses dapat membuat kebutuhanmu tidak tersampaikan.", grow: "Beri batas waktu pada refleksi, lalu komunikasikan satu hal yang sudah kamu ketahui.", coachTip: "mengubah refleksi menjadi komunikasi yang cukup jelas", triggers: [
                ["Percakapan terasa intens", "Menarik diri tanpa menjelaskan", "Minta jeda dan sepakati kapan akan kembali"],
                ["Belum yakin dengan perasaan sendiri", "Menunda respons terlalu lama", "Bagikan bahwa kamu masih memproses dan butuh waktu"]
            ] },
            expressive: { icon: "✨", name: "Penggerak Terbuka", short: "jujur dan spontan", summary: "Kamu cenderung memproses pengalaman dengan menyuarakannya dan mengajak orang lain bergerak.", who: "Keterbukaanmu memberi energi, kejelasan, dan keberanian pada percakapan.", watch: "Kecepatan bereaksi dapat mendahului pemahaman yang lebih lengkap.", grow: "Ambil satu napas, pilih tujuan percakapan, lalu sampaikan satu pesan utama.", coachTip: "memberi jeda agar ketegasan tetap terasa aman bagi kedua pihak", triggers: [
                ["Merasa tidak didengar", "Menaikkan intensitas atau mengulang pesan", "Turunkan tempo dan ajukan satu permintaan spesifik"],
                ["Ada ketidakjelasan", "Mendesak jawaban saat itu juga", "Tanyakan kapan waktu realistis untuk melanjutkan"]
            ] }
        },
        scenarios: [
            { text: "Temanmu membaca pesan penting tetapi belum membalas sejak kemarin.", choices: ["Kirim banyak pesan agar segera dijawab", "Tanya dengan tenang apakah ada waktu untuk merespons", "Anggap ia sengaja mengabaikanmu"], best: 1, feedback: ["Dorongan untuk mencari kepastian itu wajar, tetapi banyak pesan dapat menambah tekanan.", "Respons ini memisahkan fakta dari asumsi dan meminta kejelasan tanpa menuduh.", "Ini adalah kesimpulan tentang niatnya. Coba cari fakta sebelum memberi makna."] },
            { text: "Rekan satu tim mengkritik idemu di depan kelompok.", choices: ["Tanya bagian mana yang perlu diperjelas lalu lanjutkan setelah rapat", "Balas kritiknya di depan semua orang", "Diam dan menyimpan kekesalan"], best: 0, feedback: ["Kamu menjaga harga diri sekaligus membuka ruang untuk fakta dan percakapan lanjutan.", "Membalas spontan dapat menggeser tujuan dari memahami menjadi menang.", "Diam bisa menjadi jeda, tetapi sampaikan kebutuhanmu setelah emosi mereda."] },
            { text: "Rencana bersama dibatalkan mendadak dan kamu kecewa.", choices: ["Katakan dampaknya dan tanyakan kemungkinan menjadwalkan ulang", "Bilang tidak apa-apa meski sebenarnya kesal", "Memutuskan tidak akan mengajak orang itu lagi"], best: 0, feedback: ["Kamu menamai dampak dan meminta langkah yang konkret tanpa menyerang.", "Menjaga suasana boleh, tetapi perasaanmu juga perlu mendapat tempat.", "Keputusan besar saat kecewa dapat menutup kemungkinan memahami konteks."] },
            { text: "Seseorang meminta bantuan saat energimu sudah habis.", choices: ["Tetap membantu agar ia tidak kecewa", "Menolak singkat tanpa penjelasan", "Jelaskan kapasitasmu dan tawarkan waktu atau bantuan terbatas"], best: 2, feedback: ["Empati penting, tetapi mengabaikan kapasitasmu dapat menumbuhkan lelah dan kesal.", "Menolak adalah hakmu; sedikit konteks dapat membuat batas terasa lebih jelas.", "Batas yang hangat menjaga kebutuhanmu tanpa mengabaikan hubungan."] }
        ]
    }
};

growthCopy.en = {
    ...growthCopy.id,
    nav: "Growth", kicker: "KNOW YOUR PATTERN", title: "Personal Growth 🌱", subtitle: "Notice your response patterns, then choose a response that fits your values and needs.",
    introKicker: "START WITH A SMALL REFLECTION", introTitle: "How do you tend to respond?", introText: "Answer six short situations. There are no right or wrong answers—the result is a tendency, not a permanent label.",
    flow: ["Feel", "Understand", "Choose"], start: "Start reflection", privacy: "🔒 Your answers and profile stay in this browser.", step: "Question {current} of {total}", questionHint: "Choose the answer closest to your natural response.", back: "Back",
    profileKicker: "HOW I TEND TO RESPOND", retake: "Retake reflection", profileLabel: "Your main tendency", mixLabel: "Also present in how you respond", disclaimer: "This profile is flexible and may change by context—it is not a diagnosis or a fixed personality label.",
    mapKicker: "GROWTH PROFILE", mapTitle: "Your growth map", mapLabels: ["WHO I AM", "WHAT TO WATCH", "HOW I CAN GROW"], triggersKicker: "RESPONSE TRIGGERS", triggersTitle: "Moments worth noticing", triggerLabels: ["When I feel", "My natural response", "Try shifting toward"],
    compassKicker: "RESPONSE COMPASS", compassTitle: "Pause before reacting", compassIntro: "Three quick steps that let emotion be heard without letting it take over.",
    compass: [{icon:"♡",label:"FEEL",title:"Name the feeling",text:"What am I feeling, and where do I notice it in my body?"},{icon:"◇",label:"THINK",title:"Separate the facts",text:"What actually happened, and what is still an assumption?"},{icon:"↗",label:"RESPOND",title:"Choose a step",text:"What response is honest, safe, and aligned with my needs?"}],
    coachKicker: "RESPONSE COACH", coachTitle: "Shape a more intentional response", coachIntro: "Describe a situation or paste a message draft. The guidance adapts to your response tendency.", situationTab: "Situation", draftTab: "Message draft", situationLabel: "Describe your situation", draftLabel: "Paste your message draft", situationPlaceholder: "Example: My friend cancelled without letting me know...", draftPlaceholder: "Example: You always do this. I am done talking to you!", coachButtonSituation: "Help me respond", coachButtonDraft: "Review before sending", coachEmpty: "Write a situation or message draft first.", coachDisclaimer: "Local reflective guidance, not a diagnosis or substitute for professional care.", coachHeadings: ["What you may be feeling", "What may be happening", "Before responding", "A response you could try"], emotionFallback: "mixed emotions", neutralSituation: "There is a gap between what you observed and the meaning you gave it. Check the facts before deciding what another person intended.", neutralDraft: "Your message carries an important need. Making it specific and focused on one event can reduce defensiveness.", responseTemplate: "I feel {emotion} when {event}. I want to understand what happened. Can we talk about it and agree on a clear next step?", draftResponseTemplate: "I want to say this more calmly. When that happened, I felt {emotion}. I need clarity. Can we talk about what happens next?", tendencyReminder: "With your {name} tendency, you may need to {tip}", coachDone: "Reflection session saved.",
    dailyKicker: "DAILY SCENARIO", dailyTitle: "Today's practice", dailyPrompt: "Which response would you most like to practice?", dailyDone: "Today's practice is complete", dailyAgain: "You can review the other choices without changing today's answer.", practiceLabel: "practices completed", coachCountLabel: "reflection sessions", aboutLink: "About, privacy & reminders →", aboutBack: "← Back to Personal Growth",
    questions: [
        {icon:"🌧️",text:"An important plan suddenly changes. What are you most likely to do?",options:["Feel the disappointment before choosing a next step","Look for facts and alternative options","Contact the people involved and talk it through right away"]},
        {icon:"💬",text:"Someone gives criticism that feels sharp. Your first response?",options:["Pause to process how I feel","Explain my point of view immediately","Check which part of the criticism is factual"]},
        {icon:"🤝",text:"A friend tells you about a problem. You usually...",options:["Listen and validate how they feel","Help create a practical solution","Give space, then ask what they need"]},
        {icon:"⚡",text:"A conflict starts heating up. What is your natural tendency?",options:["Step back until I can think clearly","Keep everyone's feelings safe","Say directly what is bothering me"]},
        {icon:"🧩",text:"You need to make a difficult decision. What guides you most?",options:["Evidence and consequences","Talking it through to test my thinking","What best aligns with my values and feelings"]},
        {icon:"🌱",text:"After making a mistake, what happens most often?",options:["I think about its impact on others","I find the lesson and fix it quickly","I acknowledge it openly and apologize"]}
    ],
    tendencies: {
        feeling:{icon:"💗",name:"Empathic Feeler",short:"sensitive and connected",summary:"You tend to read situations through feelings, values, and their impact on others.",who:"Warmth and empathy help you notice what is not always spoken.",watch:"Other people's needs can sound louder than your own.",grow:"Validate your feelings, then ask what facts and boundaries you need.",coachTip:"separate empathy from responsibility for everyone's feelings",triggers:[["Someone seems disappointed","Blame yourself or try to fix everything","Ask what they actually need"],["A relationship feels distant","Fill the silence with assumptions","Name what you observed and ask for clarity"]]},
        thinking:{icon:"🔎",name:"Pattern Clarifier",short:"logical and directed",summary:"You tend to look for facts, patterns, and solutions that make a situation clearer.",who:"Clear thinking helps you untangle problems that feel complicated.",watch:"A quick solution can arrive before feelings have been heard.",grow:"Acknowledge the emotion before offering analysis or solutions.",coachTip:"give emotion room before moving to a solution",triggers:[["A situation feels illogical","Correct or debate the details","Ask which part matters most to the other person"],["A problem has no answer yet","Pressure yourself to solve it now","Choose one fact and one small next step"]]},
        reflective:{icon:"🌙",name:"Quiet Observer",short:"deep and considered",summary:"You tend to step back and understand feelings and context before acting.",who:"Pausing helps you see nuance and avoid a rushed response.",watch:"Processing for too long can leave your needs unspoken.",grow:"Give reflection a time limit, then communicate one thing you know.",coachTip:"turn reflection into communication that is clear enough",triggers:[["A conversation feels intense","Withdraw without explanation","Ask for a pause and agree when to return"],["You are unsure what you feel","Delay responding for too long","Say that you are processing and need time"]]},
        expressive:{icon:"✨",name:"Open Initiator",short:"honest and spontaneous",summary:"You tend to process experience by voicing it and inviting others to move with you.",who:"Openness brings energy, clarity, and courage to conversations.",watch:"The speed of a reaction can outrun fuller understanding.",grow:"Take one breath, choose the goal, then share one main message.",coachTip:"pause so directness still feels safe for both people",triggers:[["You feel unheard","Raise the intensity or repeat yourself","Slow down and make one specific request"],["Something is unclear","Push for an answer immediately","Ask when a realistic time to continue would be"]]}
    },
    scenarios: [
        {text:"A friend read an important message but has not replied since yesterday.",choices:["Send several more messages","Calmly ask whether they have time to respond","Assume they are deliberately ignoring you"],best:1,feedback:["Wanting certainty is understandable, but repeated messages can add pressure.","This separates fact from assumption and asks for clarity without accusation.","This concludes something about their intent. Look for facts before giving it meaning."]},
        {text:"A teammate criticizes your idea in front of the group.",choices:["Ask what needs clarification and continue after the meeting","Criticize them back in front of everyone","Stay silent and hold onto the resentment"],best:0,feedback:["You protect your dignity while making room for facts and a follow-up conversation.","A quick counterattack can shift the goal from understanding to winning.","Silence can be a pause, but share your need once the emotion settles."]},
        {text:"A shared plan is cancelled at the last minute and you feel disappointed.",choices:["Name the impact and ask about rescheduling","Say it is fine although you are upset","Decide never to invite them again"],best:0,feedback:["You name the impact and ask for a concrete step without attacking.","Keeping the peace is valid, but your feelings also deserve room.","A big decision made in disappointment can close off useful context."]},
        {text:"Someone asks for help when your energy is already gone.",choices:["Help anyway so they are not disappointed","Refuse abruptly without context","Explain your capacity and offer limited help or another time"],best:2,feedback:["Empathy matters, but ignoring your capacity can grow exhaustion and resentment.","You may say no; a little context can make the boundary clearer.","A warm boundary protects your needs without abandoning the relationship."]}
    ]
};

growthCopy.zh = {
    ...growthCopy.en,
    nav:"成长",kicker:"认识你的模式",title:"个人成长 🌱",subtitle:"觉察自己的回应模式，再选择更符合价值与需要的回应。",introKicker:"从小小的反思开始",introTitle:"你通常会如何回应？",introText:"回答六个简短情境。没有对错，结果只是倾向，而不是永久标签。",flow:["感受","理解","选择"],start:"开始反思",privacy:"🔒 答案和个人档案仅保存在此浏览器中。",step:"第 {current} 题，共 {total} 题",questionHint:"选择最接近你自然反应的答案。",back:"返回",
    profileKicker:"我的回应倾向",retake:"重新反思",profileLabel:"你的主要倾向",mixLabel:"你的回应中也包含",disclaimer:"此档案会随情境变化，并非诊断或固定的人格标签。",mapKicker:"成长档案",mapTitle:"你的成长地图",mapLabels:["我是谁","需要留意","如何成长"],triggersKicker:"回应触发点",triggersTitle:"值得留意的时刻",triggerLabels:["当我感到","自然反应","尝试转向"],compassKicker:"回应指南针",compassTitle:"反应前先暂停",compassIntro:"三个简短步骤，让情绪被听见，又不让它接管行动。",compass:[{icon:"♡",label:"感受",title:"说出感受",text:"我在感受什么？身体哪里能感觉到？"},{icon:"◇",label:"思考",title:"分开事实",text:"真正发生了什么？哪些仍是我的假设？"},{icon:"↗",label:"回应",title:"选择一步",text:"什么回应既诚实、安全，又符合我的需要？"}],
    coachKicker:"回应教练",coachTitle:"组织更有意识的回应",coachIntro:"描述情境或粘贴消息草稿，建议会结合你的回应倾向。",situationTab:"情境",draftTab:"消息草稿",situationLabel:"描述你的情境",draftLabel:"粘贴你的消息草稿",situationPlaceholder:"例如：朋友取消约定却没有提前告诉我……",draftPlaceholder:"例如：你总是这样，我不想再说了！",coachButtonSituation:"帮我组织回应",coachButtonDraft:"发送前检查",coachEmpty:"请先写下情境或消息草稿。",coachDisclaimer:"本地反思建议，不是诊断，也不能替代专业支持。",coachHeadings:["你可能的感受","可能正在发生什么","回应之前","可以尝试的回应"],emotionFallback:"复杂的情绪",neutralSituation:"你观察到的事情和赋予它的意义之间存在距离。在判断他人意图前，先确认事实。",neutralDraft:"你的消息承载着重要需要。把内容聚焦于一个具体事件，可以减少对方的防御。",responseTemplate:"当{event}时，我感到{emotion}。我想了解发生了什么。我们可以谈谈并确定一个清晰的下一步吗？",draftResponseTemplate:"我想更平静地表达这件事。当时我感到{emotion}，我需要的是清晰。我们可以谈谈下一步吗？",tendencyReminder:"作为{name}，你可能需要{tip}",coachDone:"反思记录已保存。",dailyKicker:"每日情境",dailyTitle:"今天的练习",dailyPrompt:"你最想练习哪一种回应？",dailyDone:"今天的练习已完成",dailyAgain:"你仍可以查看其他选项，不会改变今天的答案。",practiceLabel:"次练习已完成",coachCountLabel:"次反思",aboutLink:"关于、隐私与提醒 →",aboutBack:"← 返回个人成长",
    questions:[{icon:"🌧️",text:"一个重要计划突然改变。你最可能怎么做？",options:["先感受失望，再决定下一步","寻找事实和替代方案","马上联系相关的人谈清楚"]},{icon:"💬",text:"有人给出了尖锐的批评。你的第一反应？",options:["暂停一下，消化自己的感受","立即解释自己的观点","确认批评中哪些是事实"]},{icon:"🤝",text:"朋友向你诉说烦恼时，你通常会……",options:["倾听并肯定对方的感受","一起制定实际的解决办法","先给空间，再询问对方需要什么"]},{icon:"⚡",text:"冲突开始升温时，你的自然倾向是？",options:["暂时退开，等思路清晰","尽量照顾每个人的感受","直接说出困扰我的事情"]},{icon:"🧩",text:"必须做一个困难决定时，你最依靠什么？",options:["证据和后果","通过讨论检验想法","最符合自己价值和感受的选择"]},{icon:"🌱",text:"犯错以后，最常发生什么？",options:["考虑它对他人的影响","寻找教训并马上修正","坦率承认并道歉"]}],
    tendencies:{
        feeling:{icon:"💗",name:"共情感受者",short:"敏感而有连接",summary:"你倾向于通过感受、价值以及对他人的影响来理解情境。",who:"温暖和共情让你注意到未被说出的部分。",watch:"他人的需要可能盖过你自己的需要。",grow:"先肯定感受，再问自己需要哪些事实和界限。",coachTip:"把共情与为所有人的感受负责分开",triggers:[["他人显得失望","责怪自己或试图解决一切","询问对方真正需要什么"],["关系似乎疏远","用假设填补沉默","说出观察并请求澄清"]]},
        thinking:{icon:"🔎",name:"模式澄清者",short:"理性而有方向",summary:"你倾向于寻找事实、模式和能让情境更清楚的解决办法。",who:"清晰思考能帮助你拆解复杂问题。",watch:"解决办法有时会在感受被听见之前出现。",grow:"在分析或建议前，先承认当下的情绪。",coachTip:"在转向解决办法前给情绪一点空间",triggers:[["事情不合逻辑","纠正或争论细节","询问对方最在意哪一部分"],["问题暂时无解","逼自己马上找到答案","只确定一个事实和一个小步骤"]]},
        reflective:{icon:"🌙",name:"安静观察者",short:"深入而谨慎",summary:"你倾向于先退一步，理解感受和背景，再采取行动。",who:"暂停让你看见细微差别，避免匆忙回应。",watch:"处理太久可能让自己的需要一直没有表达。",grow:"给反思设定时间，再说出一个已经明确的部分。",coachTip:"把反思变成足够清晰的沟通",triggers:[["对话很强烈","不解释便退出","请求暂停并约定何时回来"],["不确定自己的感受","长时间拖延回应","说明自己仍在处理，需要一些时间"]]},
        expressive:{icon:"✨",name:"开放行动者",short:"坦诚而自然",summary:"你倾向于通过说出来处理经历，并邀请他人一起行动。",who:"开放为对话带来能量、清晰和勇气。",watch:"反应速度可能超过对情境的完整理解。",grow:"先呼吸一次，确定对话目标，再表达一个核心信息。",coachTip:"先暂停，让直接表达对双方仍然安全",triggers:[["觉得没有被听见","提高强度或重复信息","放慢速度，只提出一个具体请求"],["事情不明确","要求马上得到答案","询问何时继续更现实"]]}
    },
    scenarios:[{text:"朋友读了重要消息，但从昨天起还没有回复。",choices:["继续发送很多消息","平静询问对方是否有时间回复","认定对方故意忽略你"],best:1,feedback:["想得到确定感很自然，但连续消息可能增加压力。","这把事实与假设分开，并在不指责的情况下请求澄清。","这是对意图的结论。先寻找事实，再赋予意义。"]},{text:"队友在大家面前批评你的想法。",choices:["询问需要澄清的部分，会后继续谈","当众反击对方","保持沉默，把不满留在心里"],best:0,feedback:["你维护了自尊，也为事实和后续沟通留下空间。","立刻反击可能让目标从理解变成获胜。","沉默可以是暂停，但情绪稳定后仍要表达需要。"]},{text:"共同计划临时取消，你很失望。",choices:["说明影响并询问能否改期","虽然生气仍说没关系","决定以后不再邀请对方"],best:0,feedback:["你说清了影响，并在不攻击的情况下提出具体下一步。","维持气氛可以理解，但你的感受也需要空间。","失望时做重大决定，可能阻断对背景的理解。"]},{text:"精力耗尽时，有人请你帮忙。",choices:["仍然帮忙，避免对方失望","不解释便直接拒绝","说明自己的容量，提供有限帮助或另约时间"],best:2,feedback:["共情很重要，但忽视容量会积累疲惫和不满。","你有权拒绝；一点背景会让界限更清楚。","温和的界限既保护自己，也没有放弃关系。"]}]
};
